### PR TITLE
Added publishing ability from MM-MQTT module and Updated Documentation

### PR DESCRIPTION
**Pull request by cybex-dev**
### Changes:
Added explanations:
 * MQTT protocol
 * configuration details, etc.

### Addition:
Added functionality to publish data to MQTT servers using `MQTT_PUBLISH` notification.

The format for publishing data is as follows:

```this.sendNotification(notification, payload, sender)```

#### where 
 - `notification`: your notification which you intended to broadcast (matching notifications set in configuration file)
 - `payload`: the data you wish to publish to MQTT server

### CODE REVIEW

**Comment by cybex-dev** [comment]
Apologies for the Closing of the PR.

**Comment by ottopaulsen** [comment]
Hi Charles, and thank you for contributing. I am sorry I have been using some time reviewing this. The reason is that I have been wondering whether to add this functionality or not. You see, I am very much for separation of concerns, and I prefer multiple smaller modules in stead of one large. I am not sure mixing publishing and subscribing in the same module is a good idea. These two features are in fact very different. The only thing they have in common is the connection to the MQ, and as you can see, the code is increasing very much my adding this feature.

So I actually believe that publishing messages should be done in a separate module, that should be designed to deal with only that.

I am also a bit curious, what are the really good use cases for publishing from the mirror/screen? It is a place where information is displayed, and not primarily created. I am sure there are good use cases for publishing also from the screen, but do you have any examples? I believe it should be for information that originates in the screen, as I do not think the screen should be used as a message broker or an orchestrator.

I am looking forward to hearing your response to my concerns.

**Comment by cybex-dev** [comment]
> Hi Charles, and thank you for contributing. I am sorry I have been using some time reviewing this. The reason is that I have been wondering whether to add this functionality or not. You see, I am very much for separation of concerns, and I prefer multiple smaller modules in stead of one large. I am not sure mixing publishing and subscribing in the same module is a good idea. These two features are in fact very different. The only thing they have in common is the connection to the MQ, and as you can see, the code is increasing very much my adding this feature.
> 
> So I actually believe that publishing messages should be done in a separate module, that should be designed to deal with only that.
> 
> I am also a bit curious, what are the really good use cases for publishing from the mirror/screen? It is a place where information is displayed, and not primarily created. I am sure there are good use cases for publishing also from the screen, but do you have any examples? I believe it should be for information that originates in the screen, as I do not think the screen should be used as a message broker or an orchestrator.
> 
> I am looking forward to hearing your response to my concerns.

Good day Otto. I hope you are well. 

**Addition of publishing ability:**
The minor additions I have made to your project is for the MMM-MQTT Subscriber to be a publisher to, to a MQTT Broker. Note however that the addition doesn't make it a broker, but only a publisher i.e. we are publishing data/info for specified topics to a local/web-based MQTT broker.

**Regarding the separation of concerns:** 
I was tempted to create my own module, however this seemed quite redundant as most of the code used for MQTT communication has already been created in this module. Thus, having to recreated it seemed quite unnecessary. Further, since the module is named MMM-MQTT, I saw it fit to add a publishing aspect to it too, thus being a full MQTT 'client' of sorts rather than a subscriber only.

**Use cases:**
You may have noticed the format and capability of publishing data. Each topic subscribed to can post data from various notifications using the _MM-NotificationMechanism_. Thus, any activity from the MagicMirror can be published to a MQTT broker.

A specific use case is the MM-Calender. A user may subscribe to a RSS feed (or any other feed) for calender events. This in turn can be listened (or subscribed to) using the MMM-MQTT module. When a new calender event (or even news article is added), this info can be e.g.rebroadcasted to a local MQTT broker, where any subscribers can make do with it as needed e.g. flash a lightbulb or read out using TTS on e.g. OpenHAB. Using the Spotify module, (possible) notifications can be added when a song changes, being broadcasted to a local IoT instance and being processed accordingly.

_For my use, this forms part of my research in IoT frameworks and various experiments in my master's research._

**Comment by Ryton** [comment]
Interesting discussion /contrib!

_>> This in turn can be listened (or subscribed to) using the MMM-MQTT module._ 
I do support the use case of this feature myself, and would like to add another use case:

For people with limited coding experience (i'm a total JS-noob :s ) , the information gathered by a few other MM-modules are not easy to implement in personal code / cron-scripts, publishing to mqtt. 
On the other hand, it is quite straightfoward to obtain said data through the pre-coded MM-interface / API-modules.

YES:  It would therefore make sense/be useful to publish some of that obtained info on a broker again, running parallel /continuously on a separate server, so it can be picked up by other visualisation services based on that information stream.
In my case: PV consumption data (local, gathered from [bertieuk/MMM-SolarEdge](https://github.com/bertieuk/MMM-SolarEdge); ideally to be republished to a local mqtt server (on a different machine)), containing electricity use data & visualisation software.

NO: Though i also understand your reluctance, Otto: the visualisation software may not run continuously, so it'd be more logical to write backend code for this function. 

PO: Can a MM be executed without visualisation? Can we run multiple instances, each with a config file?

**Comment by ottopaulsen** [comment]
Thank you for contributing to the discussion, @Ryton. More opinions are welcome, as I am not certain what is the right choice here. I am pretty sure that a preferred solution is to handle all the mentioned use cases on a back-end solution. An example I would try is Node-RED, that is perfect for this kind of usage. However, it would absolutely be nice to be able to publish from the MM as well, as it would be pretty easy to set up, and I believe there are many use cases where this would be very useful.

My only concern is to mix this in to the same module. It increases complexity, and as a software developer, I want to avoid that. I think I would prefer an MMM-MQTT-Publisher module instead, that would do only publishing. Such a module would be much simpler.

Why don't you, @cybex-dev, try to split the publishing functionality into such a separate module? Maintaining and using multiple small modules is preferred over maintaining large complex modules, as the maintenance cost increases exponentially with complexity.

**Comment by Ryton** [comment]
Thank you for the referral, @ottopaulsen.  I might look into Node-Red for my application as a secondary option, as my MQTT broker is currently already running as a Paho JavaScript client on a OpenWRT Backfire-based AVR microcontroller (written/implemented by another githubber), I will first try to publish the data on that platform and sub to it from MM, but that will require some study of that platform/code and the specific API.

**Comment by cybex-dev** [comment]
> Thank you for contributing to the discussion, @Ryton. More opinions are welcome, as I am not certain what is the right choice here. I am pretty sure that a preferred solution is to handle all the mentioned use cases on a back-end solution. An example I would try is Node-RED, that is perfect for this kind of usage. However, it would absolutely be nice to be able to publish from the MM as well, as it would be pretty easy to set up, and I believe there are many use cases where this would be very useful.
> 
> My only concern is to mix this in to the same module. It increases complexity, and as a software developer, I want to avoid that. I think I would prefer an MMM-MQTT-Publisher module instead, that would do only publishing. Such a module would be much simpler.
> 
> Why don't you, @cybex-dev, try to split the publishing functionality into such a separate module? Maintaining and using multiple small modules is preferred over maintaining large complex modules, as the maintenance cost increases exponentially with complexity.

Hi Otto. Sorry for not responding sooner. If you feel that I should seperate the modules, where this module will become e.g. MM-MQTT-Publish, I will gladly do so. 

I will borrow some of you code then ;) (and give credit, of course!)

**Comment by cybex-dev** [comment]
@ottopaulsen Hi. I hope you don't mind, I will be 'stealing' some of you MQTT code for the publisher module I am busy with. Thanks in advance ;)

Will naturally give credit where it is due.

**Comment by ottopaulsen** [comment]
Of course :-) Feel free to copy whatever you like!

Otto

lør. 22. jun. 2019 kl. 20:12 skrev Charles Dyason <notifications@github.com

**Comment by cybex-dev** [comment]
Last time opening/closing ;)

[MMM-MQTT-Publisher](https://github.com/cybex-dev/MMM-MQTT-Publisher) module added. 

@Ryton

Thanks @ottopaulsen

**Pull request closed without merging**
